#!/usr/bin/env python3

import os
from pathlib import Path

structure = {
    "beacom-mobile/gradle.properties": "",
    "beacom-mobile/settings.gradle.kts": "",
    "beacom-mobile/build.gradle.kts": "",
    "beacom-mobile/gradle/wrapper/gradle-wrapper.properties": "",
    "beacom-mobile/gradle/wrapper/gradle-wrapper.jar": "",
    "beacom-mobile/gradlew": "",
    "beacom-mobile/gradlew.bat": "",
    "beacom-mobile/.gitignore": "",
    "beacom-mobile/README.md": "",
    
    "beacom-mobile/shared/build.gradle.kts": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/App.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/di/KoinModule.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/di/NetworkModule.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/di/RepositoryModule.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/di/ViewModelModule.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/api/BeacomApi.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/api/AuthApi.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/api/BillingApi.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/api/UsageApi.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/api/MarketplaceApi.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/api/HardwareApi.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/api/SupportApi.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/grpc/GrpcClient.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/grpc/AuthGrpcClient.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/grpc/BillingGrpcClient.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/grpc/UsageGrpcClient.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/grpc/MarketplaceGrpcClient.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/models/User.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/models/Subscription.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/models/Payment.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/models/Usage.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/models/Bundle.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/models/Device.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/models/Product.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/models/Order.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/models/SupportTicket.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/repository/AuthRepository.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/repository/UserRepository.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/repository/BillingRepository.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/repository/UsageRepository.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/repository/MarketplaceRepository.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/repository/HardwareRepository.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/repository/SupportRepository.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/local/Database.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/local/SettingsStore.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/data/local/CacheManager.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/auth/LoginUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/auth/RegisterUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/auth/LogoutUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/auth/RefreshTokenUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/billing/GetSubscriptionUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/billing/PurchaseBundleUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/billing/TopUpUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/usage/GetUsageStatsUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/usage/GetUsageHistoryUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/marketplace/GetProductsUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/marketplace/PurchaseProductUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/marketplace/BuyAirtimeUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/hardware/GetDevicesUseCase.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/domain/usecase/hardware/ConfigureRouterUseCase.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/navigation/NavGraph.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/navigation/Screen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/navigation/Navigator.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/theme/Theme.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/theme/Color.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/theme/Typography.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/theme/Spacing.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/theme/Shape.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/components/BeacomButton.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/components/BeacomTextField.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/components/BeacomCard.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/components/BeacomTopBar.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/components/BeacomBottomNav.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/components/LoadingIndicator.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/components/ErrorView.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/components/UsageChart.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/components/DataMeter.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/auth/LoginScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/auth/LoginViewModel.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/auth/RegisterScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/auth/RegisterViewModel.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/auth/ForgotPasswordScreen.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/home/HomeScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/home/HomeViewModel.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/home/DashboardCard.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/home/QuickActionsCard.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/usage/UsageScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/usage/UsageViewModel.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/usage/UsageHistoryScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/usage/UsageDetailsScreen.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/billing/BillingScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/billing/BillingViewModel.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/billing/BundlesScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/billing/TopUpScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/billing/PaymentMethodScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/billing/PaymentHistoryScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/billing/InvoicesScreen.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/marketplace/MarketplaceScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/marketplace/MarketplaceViewModel.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/marketplace/AirtimeScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/marketplace/BillPaymentScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/marketplace/VouchersScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/marketplace/ProductDetailsScreen.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/hardware/DevicesScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/hardware/DevicesViewModel.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/hardware/RouterConfigScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/hardware/DeviceDiagnosticsScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/hardware/FirmwareUpdateScreen.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/support/SupportScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/support/SupportViewModel.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/support/TicketsScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/support/CreateTicketScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/support/LiveChatScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/support/FaqScreen.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/profile/ProfileScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/profile/ProfileViewModel.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/profile/EditProfileScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/profile/SettingsScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/profile/NotificationsSettingsScreen.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/presentation/screens/profile/SecurityScreen.kt": "",
    
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/util/Constants.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/util/Result.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/util/NetworkUtils.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/util/DateUtils.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/util/FormatUtils.kt": "",
    "beacom-mobile/shared/src/commonMain/kotlin/com/beacom/app/util/ValidationUtils.kt": "",
    
    "beacom-mobile/shared/src/androidMain/kotlin/com/beacom/app/Platform.android.kt": "",
    "beacom-mobile/shared/src/androidMain/kotlin/com/beacom/app/di/PlatformModule.android.kt": "",
    
    "beacom-mobile/shared/src/iosMain/kotlin/com/beacom/app/Platform.ios.kt": "",
    "beacom-mobile/shared/src/iosMain/kotlin/com/beacom/app/di/PlatformModule.ios.kt": "",
    
    "beacom-mobile/shared/src/commonTest/kotlin/com/beacom/app/data/repository/AuthRepositoryTest.kt": "",
    "beacom-mobile/shared/src/commonTest/kotlin/com/beacom/app/data/repository/BillingRepositoryTest.kt": "",
    "beacom-mobile/shared/src/commonTest/kotlin/com/beacom/app/domain/usecase/LoginUseCaseTest.kt": "",
    "beacom-mobile/shared/src/commonTest/kotlin/com/beacom/app/presentation/screens/auth/LoginViewModelTest.kt": "",
    
    "beacom-mobile/androidApp/build.gradle.kts": "",
    "beacom-mobile/androidApp/proguard-rules.pro": "",
    "beacom-mobile/androidApp/src/main/AndroidManifest.xml": "",
    "beacom-mobile/androidApp/src/main/kotlin/com/beacom/app/android/MainActivity.kt": "",
    "beacom-mobile/androidApp/src/main/kotlin/com/beacom/app/android/BeacomApplication.kt": "",
    "beacom-mobile/androidApp/src/main/kotlin/com/beacom/app/android/services/BeacomFirebaseMessagingService.kt": "",
    "beacom-mobile/androidApp/src/main/res/values/strings.xml": "",
    "beacom-mobile/androidApp/src/main/res/values/colors.xml": "",
    "beacom-mobile/androidApp/src/main/res/values/themes.xml": "",
    "beacom-mobile/androidApp/src/main/res/drawable/ic_launcher_background.xml": "",
    "beacom-mobile/androidApp/src/main/res/mipmap-hdpi/ic_launcher.png": "",
    "beacom-mobile/androidApp/src/main/res/mipmap-mdpi/ic_launcher.png": "",
    "beacom-mobile/androidApp/src/main/res/mipmap-xhdpi/ic_launcher.png": "",
    "beacom-mobile/androidApp/src/main/res/mipmap-xxhdpi/ic_launcher.png": "",
    "beacom-mobile/androidApp/src/main/res/mipmap-xxxhdpi/ic_launcher.png": "",
    
    "beacom-mobile/iosApp/iosApp.xcodeproj/project.pbxproj": "",
    "beacom-mobile/iosApp/iosApp/Info.plist": "",
    "beacom-mobile/iosApp/iosApp/BeacomApp.swift": "",
    "beacom-mobile/iosApp/iosApp/ContentView.swift": "",
    "beacom-mobile/iosApp/iosApp/AppDelegate.swift": "",
    "beacom-mobile/iosApp/iosApp/Assets.xcassets/AppIcon.appiconset/Contents.json": "",
    "beacom-mobile/iosApp/iosApp/Assets.xcassets/Contents.json": "",
    
    "beacom-web/package.json": "",
    "beacom-web/tsconfig.json": "",
    "beacom-web/vite.config.ts": "",
    "beacom-web/tailwind.config.js": "",
    "beacom-web/postcss.config.js": "",
    "beacom-web/.env.example": "",
    "beacom-web/.gitignore": "",
    "beacom-web/README.md": "",
    "beacom-web/index.html": "",
    
    "beacom-web/public/favicon.ico": "",
    "beacom-web/public/logo.svg": "",
    "beacom-web/public/manifest.json": "",
    "beacom-web/public/robots.txt": "",
    
    "beacom-web/src/main.tsx": "",
    "beacom-web/src/App.tsx": "",
    "beacom-web/src/vite-env.d.ts": "",
    
    "beacom-web/src/config/api.ts": "",
    "beacom-web/src/config/routes.ts": "",
    "beacom-web/src/config/constants.ts": "",
    
    "beacom-web/src/lib/api/client.ts": "",
    "beacom-web/src/lib/api/auth.ts": "",
    "beacom-web/src/lib/api/billing.ts": "",
    "beacom-web/src/lib/api/usage.ts": "",
    "beacom-web/src/lib/api/marketplace.ts": "",
    "beacom-web/src/lib/api/hardware.ts": "",
    "beacom-web/src/lib/api/support.ts": "",
    "beacom-web/src/lib/api/admin.ts": "",
    
    "beacom-web/src/lib/grpc/client.ts": "",
    "beacom-web/src/lib/grpc/auth.ts": "",
    "beacom-web/src/lib/grpc/billing.ts": "",
    "beacom-web/src/lib/grpc/usage.ts": "",
    
    "beacom-web/src/lib/utils/format.ts": "",
    "beacom-web/src/lib/utils/validation.ts": "",
    "beacom-web/src/lib/utils/date.ts": "",
    "beacom-web/src/lib/utils/storage.ts": "",
    
    "beacom-web/src/types/user.ts": "",
    "beacom-web/src/types/subscription.ts": "",
    "beacom-web/src/types/payment.ts": "",
    "beacom-web/src/types/usage.ts": "",
    "beacom-web/src/types/device.ts": "",
    "beacom-web/src/types/product.ts": "",
    "beacom-web/src/types/ticket.ts": "",
    
    "beacom-web/src/hooks/useAuth.ts": "",
    "beacom-web/src/hooks/useBilling.ts": "",
    "beacom-web/src/hooks/useUsage.ts": "",
    "beacom-web/src/hooks/useMarketplace.ts": "",
    "beacom-web/src/hooks/useHardware.ts": "",
    "beacom-web/src/hooks/useWebSocket.ts": "",
    
    "beacom-web/src/store/authStore.ts": "",
    "beacom-web/src/store/userStore.ts": "",
    "beacom-web/src/store/billingStore.ts": "",
    "beacom-web/src/store/usageStore.ts": "",
    "beacom-web/src/store/themeStore.ts": "",
    
    "beacom-web/src/components/ui/Button.tsx": "",
    "beacom-web/src/components/ui/Input.tsx": "",
    "beacom-web/src/components/ui/Card.tsx": "",
    "beacom-web/src/components/ui/Modal.tsx": "",
    "beacom-web/src/components/ui/Toast.tsx": "",
    "beacom-web/src/components/ui/Spinner.tsx": "",
    "beacom-web/src/components/ui/Badge.tsx": "",
    "beacom-web/src/components/ui/Dropdown.tsx": "",
    "beacom-web/src/components/ui/Table.tsx": "",
    "beacom-web/src/components/ui/Tabs.tsx": "",
    "beacom-web/src/components/ui/Chart.tsx": "",
    
    "beacom-web/src/components/layout/Header.tsx": "",
    "beacom-web/src/components/layout/Sidebar.tsx": "",
    "beacom-web/src/components/layout/Footer.tsx": "",
    "beacom-web/src/components/layout/Navigation.tsx": "",
    "beacom-web/src/components/layout/Layout.tsx": "",
    "beacom-web/src/components/layout/DashboardLayout.tsx": "",
    
    "beacom-web/src/components/common/DataMeter.tsx": "",
    "beacom-web/src/components/common/UsageChart.tsx": "",
    "beacom-web/src/components/common/BundleCard.tsx": "",
    "beacom-web/src/components/common/DeviceCard.tsx": "",
    "beacom-web/src/components/common/ProductCard.tsx": "",
    "beacom-web/src/components/common/PaymentMethodCard.tsx": "",
    "beacom-web/src/components/common/NotificationBell.tsx": "",
    "beacom-web/src/components/common/SearchBar.tsx": "",
    
    "beacom-web/src/pages/auth/Login.tsx": "",
    "beacom-web/src/pages/auth/Register.tsx": "",
    "beacom-web/src/pages/auth/ForgotPassword.tsx": "",
    "beacom-web/src/pages/auth/ResetPassword.tsx": "",
    "beacom-web/src/pages/auth/VerifyEmail.tsx": "",
    
    "beacom-web/src/pages/home/Landing.tsx": "",
    "beacom-web/src/pages/home/Dashboard.tsx": "",
    "beacom-web/src/pages/home/Overview.tsx": "",
    
    "beacom-web/src/pages/usage/Usage.tsx": "",
    "beacom-web/src/pages/usage/UsageHistory.tsx": "",
    "beacom-web/src/pages/usage/UsageDetails.tsx": "",
    
    "beacom-web/src/pages/billing/Billing.tsx": "",
    "beacom-web/src/pages/billing/Bundles.tsx": "",
    "beacom-web/src/pages/billing/TopUp.tsx": "",
    "beacom-web/src/pages/billing/PaymentMethods.tsx": "",
    "beacom-web/src/pages/billing/PaymentHistory.tsx": "",
    "beacom-web/src/pages/billing/Invoices.tsx": "",
    
    "beacom-web/src/pages/marketplace/Marketplace.tsx": "",
    "beacom-web/src/pages/marketplace/Airtime.tsx": "",
    "beacom-web/src/pages/marketplace/BillPayment.tsx": "",
    "beacom-web/src/pages/marketplace/Vouchers.tsx": "",
    "beacom-web/src/pages/marketplace/ProductDetails.tsx": "",
    
    "beacom-web/src/pages/hardware/Devices.tsx": "",
    "beacom-web/src/pages/hardware/RouterConfig.tsx": "",
    "beacom-web/src/pages/hardware/Diagnostics.tsx": "",
    "beacom-web/src/pages/hardware/FirmwareUpdate.tsx": "",
    
    "beacom-web/src/pages/support/Support.tsx": "",
    "beacom-web/src/pages/support/Tickets.tsx": "",
    "beacom-web/src/pages/support/CreateTicket.tsx": "",
    "beacom-web/src/pages/support/TicketDetails.tsx": "",
    "beacom-web/src/pages/support/LiveChat.tsx": "",
    "beacom-web/src/pages/support/Faq.tsx": "",
    
    "beacom-web/src/pages/profile/Profile.tsx": "",
    "beacom-web/src/pages/profile/EditProfile.tsx": "",
    "beacom-web/src/pages/profile/Settings.tsx": "",
    "beacom-web/src/pages/profile/Security.tsx": "",
    "beacom-web/src/pages/profile/Notifications.tsx": "",
    
    "beacom-web/src/pages/admin/Dashboard.tsx": "",
    "beacom-web/src/pages/admin/Users.tsx": "",
    "beacom-web/src/pages/admin/Subscriptions.tsx": "",
    "beacom-web/src/pages/admin/Payments.tsx": "",
    "beacom-web/src/pages/admin/Network.tsx": "",
    "beacom-web/src/pages/admin/Hardware.tsx": "",
    "beacom-web/src/pages/admin/Support.tsx": "",
    "beacom-web/src/pages/admin/Reports.tsx": "",
    "beacom-web/src/pages/admin/Analytics.tsx": "",
    "beacom-web/src/pages/admin/Settings.tsx": "",
    
    "beacom-web/src/styles/globals.css": "",
    "beacom-web/src/styles/variables.css": "",
    "beacom-web/src/styles/animations.css": "",
    
    "beacom-web/src/assets/images/.gitkeep": "",
    "beacom-web/src/assets/icons/.gitkeep": "",
    "beacom-web/src/assets/fonts/.gitkeep": "",
    
    "beacom-web/src/routes/index.tsx": "",
    "beacom-web/src/routes/PrivateRoute.tsx": "",
    "beacom-web/src/routes/PublicRoute.tsx": "",
    "beacom-web/src/routes/AdminRoute.tsx": "",
    
    "beacom-web/src/services/websocket.ts": "",
    "beacom-web/src/services/notifications.ts": "",
    "beacom-web/src/services/analytics.ts": "",
    "beacom-web/src/services/errorTracking.ts": "",
    
    "beacom-web/src/middleware/auth.ts": "",
    "beacom-web/src/middleware/errorHandler.ts": "",
    
    "beacom-web/src/contexts/AuthContext.tsx": "",
    "beacom-web/src/contexts/ThemeContext.tsx": "",
    "beacom-web/src/contexts/NotificationContext.tsx": "",
    
    "beacom-web/tests/setup.ts": "",
    "beacom-web/tests/unit/components/Button.test.tsx": "",
    "beacom-web/tests/unit/hooks/useAuth.test.ts": "",
    "beacom-web/tests/integration/auth.test.tsx": "",
    "beacom-web/tests/e2e/login.spec.ts": "",
    
    "beacom-admin/package.json": "",
    "beacom-admin/tsconfig.json": "",
    "beacom-admin/vite.config.ts": "",
    "beacom-admin/tailwind.config.js": "",
    "beacom-admin/.env.example": "",
    "beacom-admin/.gitignore": "",
    "beacom-admin/README.md": "",
    "beacom-admin/index.html": "",
    
    "beacom-admin/src/main.tsx": "",
    "beacom-admin/src/App.tsx": "",
    
    "beacom-admin/src/config/api.ts": "",
    "beacom-admin/src/config/routes.ts": "",
    
    "beacom-admin/src/lib/api/client.ts": "",
    "beacom-admin/src/lib/api/users.ts": "",
    "beacom-admin/src/lib/api/subscriptions.ts": "",
    "beacom-admin/src/lib/api/payments.ts": "",
    "beacom-admin/src/lib/api/network.ts": "",
    "beacom-admin/src/lib/api/hardware.ts": "",
    "beacom-admin/src/lib/api/support.ts": "",
    "beacom-admin/src/lib/api/reports.ts": "",
    "beacom-admin/src/lib/api/analytics.ts": "",
    
    "beacom-admin/src/lib/grpc/client.ts": "",
    "beacom-admin/src/lib/grpc/admin.ts": "",
    "beacom-admin/src/lib/grpc/network.ts": "",
    
    "beacom-admin/src/types/admin.ts": "",
    "beacom-admin/src/types/network.ts": "",
    "beacom-admin/src/types/reports.ts": "",
    
    "beacom-admin/src/hooks/useUsers.ts": "",
    "beacom-admin/src/hooks/useNetwork.ts": "",
    "beacom-admin/src/hooks/useReports.ts": "",
    "beacom-admin/src/hooks/useAnalytics.ts": "",
    
    "beacom-admin/src/store/adminStore.ts": "",
    "beacom-admin/src/store/networkStore.ts": "",
    
    "beacom-admin/src/components/ui/DataTable.tsx": "",
    "beacom-admin/src/components/ui/DatePicker.tsx": "",
    "beacom-admin/src/components/ui/MultiSelect.tsx": "",
    "beacom-admin/src/components/ui/FileUpload.tsx": "",
    "beacom-admin/src/components/ui/CodeEditor.tsx": "",
    
    "beacom-admin/src/components/layout/AdminLayout.tsx": "",
    "beacom-admin/src/components/layout/AdminHeader.tsx": "",
    "beacom-admin/src/components/layout/AdminSidebar.tsx": "",
    
    "beacom-admin/src/components/dashboard/StatsCard.tsx": "",
    "beacom-admin/src/components/dashboard/RevenueChart.tsx": "",
    "beacom-admin/src/components/dashboard/UsersChart.tsx": "",
    "beacom-admin/src/components/dashboard/NetworkStatus.tsx": "",
    "beacom-admin/src/components/dashboard/RecentActivity.tsx": "",
    "beacom-admin/src/components/dashboard/Alerts.tsx": "",
    
    "beacom-admin/src/components/users/UserTable.tsx": "",
    "beacom-admin/src/components/users/UserDetails.tsx": "",
    "beacom-admin/src/components/users/UserForm.tsx": "",
    "beacom-admin/src/components/users/UserActions.tsx": "",
    
    "beacom-admin/src/components/network/NodeMap.tsx": "",
    "beacom-admin/src/components/network/NodeList.tsx": "",
    "beacom-admin/src/components/network/NodeDetails.tsx": "",
    "beacom-admin/src/components/network/NetworkTopology.tsx": "",
    "beacom-admin/src/components/network/BandwidthMonitor.tsx": "",
    
    "beacom-admin/src/components/hardware/DeviceTable.tsx": "",
    "beacom-admin/src/components/hardware/DeviceDetails.tsx": "",
    "beacom-admin/src/components/hardware/FirmwareManager.tsx": "",
    "beacom-admin/src/components/hardware/ProvisioningTool.tsx": "",
    
    "beacom-admin/src/components/support/TicketQueue.tsx": "",
    "beacom-admin/src/components/support/TicketDetails.tsx": "",
    "beacom-admin/src/components/support/TicketAssignment.tsx": "",
    
    "beacom-admin/src/components/reports/ReportBuilder.tsx": "",
    "beacom-admin/src/components/reports/ReportViewer.tsx": "",
    "beacom-admin/src/components/reports/ExportOptions.tsx": "",
    
    "beacom-admin/src/pages/Dashboard.tsx": "",
    "beacom-admin/src/pages/Users.tsx": "",
    "beacom-admin/src/pages/UserDetails.tsx": "",
    "beacom-admin/src/pages/Subscriptions.tsx": "",
    "beacom-admin/src/pages/Payments.tsx": "",
    "beacom-admin/src/pages/Network.tsx": "",
    "beacom-admin/src/pages/NetworkNode.tsx": "",
    "beacom-admin/src/pages/Hardware.tsx": "",
    "beacom-admin/src/pages/Support.tsx": "",
    "beacom-admin/src/pages/TicketDetails.tsx": "",
    "beacom-admin/src/pages/Reports.tsx": "",
    "beacom-admin/src/pages/Analytics.tsx": "",
    "beacom-admin/src/pages/Settings.tsx": "",
    "beacom-admin/src/pages/AuditLog.tsx": "",
    
    "beacom-admin/src/routes/index.tsx": "",
    
    "beacom-admin/src/styles/globals.css": "",
    
    "beacom-admin/tests/setup.ts": "",
    
    "beacom-marketing/package.json": "",
    "beacom-marketing/tsconfig.json": "",
    "beacom-marketing/next.config.js": "",
    "beacom-marketing/tailwind.config.js": "",
    "beacom-marketing/.env.example": "",
    "beacom-marketing/.gitignore": "",
    "beacom-marketing/README.md": "",
    
    "beacom-marketing/public/favicon.ico": "",
    "beacom-marketing/public/logo.svg": "",
    "beacom-marketing/public/images/.gitkeep": "",
    
    "beacom-marketing/src/app/layout.tsx": "",
    "beacom-marketing/src/app/page.tsx": "",
    "beacom-marketing/src/app/about/page.tsx": "",
    "beacom-marketing/src/app/pricing/page.tsx": "",
    "beacom-marketing/src/app/coverage/page.tsx": "",
    "beacom-marketing/src/app/hardware/page.tsx": "",
    "beacom-marketing/src/app/marketplace/page.tsx": "",
    "beacom-marketing/src/app/business/page.tsx": "",
    "beacom-marketing/src/app/blog/page.tsx": "",
    "beacom-marketing/src/app/blog/[slug]/page.tsx": "",
    "beacom-marketing/src/app/contact/page.tsx": "",
    "beacom-marketing/src/app/privacy/page.tsx": "",
    "beacom-marketing/src/app/terms/page.tsx": "",
    
    "beacom-marketing/src/components/layout/Header.tsx": "",
    "beacom-marketing/src/components/layout/Footer.tsx": "",
    "beacom-marketing/src/components/layout/Navigation.tsx": "",
    
    "beacom-marketing/src/components/home/Hero.tsx": "",
    "beacom-marketing/src/components/home/Features.tsx": "",
    "beacom-marketing/src/components/home/Pricing.tsx": "",
    "beacom-marketing/src/components/home/Testimonials.tsx": "",
    "beacom-marketing/src/components/home/Coverage.tsx": "",
    "beacom-marketing/src/components/home/CallToAction.tsx": "",
    
    "beacom-marketing/src/components/ui/Button.tsx": "",
    "beacom-marketing/src/components/ui/Card.tsx": "",
    "beacom-marketing/src/components/ui/Input.tsx": "",
    
    "beacom-marketing/src/lib/api.ts": "",
    "beacom-marketing/src/lib/utils.ts": "",
    
    "beacom-marketing/src/styles/globals.css": "",
}

def create_structure(base_path="."):
    base = Path(base_path)
    
    for file_path in structure.keys():
        full_path = base / file_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.touch(exist_ok=True)
    
    print(f"✅ Created {len(structure)} files and directories")
    print(f"📱 Beacom Mobile (KMP + Compose): beacom-mobile/")
    print(f"🌐 Beacom Web Portal (React): beacom-web/")
    print(f"🔧 Beacom Admin Dashboard (React): beacom-admin/")
    print(f"🚀 Beacom Marketing Site (Next.js): beacom-marketing/")

if __name__ == "__main__":
    create_structure()
